"""add pee_amount stool_amount to diapers

Revision ID: 0f1dce8f5d42
Revises: 8544e719c29e
Create Date: 2026-04-23 09:12:21.128559+02:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0f1dce8f5d42'
down_revision: str | Sequence[str] | None = '8544e719c29e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diapers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pee_amount', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
        batch_op.add_column(sa.Column('stool_amount', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diapers', schema=None) as batch_op:
        batch_op.drop_column('stool_amount')
        batch_op.drop_column('pee_amount')

    # ### end Alembic commands ###
