"""add dismissed_at to warning_states

Revision ID: 8544e719c29e
Revises: ebbb8202b0c2
Create Date: 2026-04-23 09:10:59.948512+02:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8544e719c29e'
down_revision: str | Sequence[str] | None = 'ebbb8202b0c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warning_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dismissed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warning_states', schema=None) as batch_op:
        batch_op.drop_column('dismissed_at')

    # ### end Alembic commands ###
