"""initial schema

Revision ID: e00429d9a581
Revises: 
Create Date: 2026-04-21 18:03:43.168155+02:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e00429d9a581'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('birth_at', sa.DateTime(), nullable=False),
    sa.Column('birth_weight_g', sa.Integer(), nullable=True),
    sa.Column('birth_length_cm', sa.Float(), nullable=True),
    sa.Column('birth_head_cm', sa.Float(), nullable=True),
    sa.Column('gestational_weeks', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_children_birth_at'), ['birth_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_children_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_children_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('ha_user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('external_token', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ha_user_id'), ['ha_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    op.create_table('who_lms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('age_days', sa.Integer(), nullable=False),
    sa.Column('L', sa.Float(), nullable=False),
    sa.Column('M', sa.Float(), nullable=False),
    sa.Column('S', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('who_lms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_who_lms_age_days'), ['age_days'], unique=False)
        batch_op.create_index(batch_op.f('ix_who_lms_indicator'), ['indicator'], unique=False)
        batch_op.create_index(batch_op.f('ix_who_lms_sex'), ['sex'], unique=False)

    op.create_table('appointments',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('reaction', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_mother_id'), ['mother_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_scheduled_at'), ['scheduled_at'], unique=False)

    op.create_table('diapers',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('pee', sa.Boolean(), nullable=False),
    sa.Column('stool', sa.Boolean(), nullable=False),
    sa.Column('pee_intensity', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('stool_color', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('stool_consistency', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diapers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diapers_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_diapers_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diapers_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('feedings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('breast_side', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('duration_left_min', sa.Integer(), nullable=True),
    sa.Column('duration_right_min', sa.Integer(), nullable=True),
    sa.Column('bottle_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('bottle_offered_ml', sa.Integer(), nullable=True),
    sa.Column('bottle_taken_ml', sa.Integer(), nullable=True),
    sa.Column('spit_up', sa.Boolean(), nullable=False),
    sa.Column('spit_up_amount', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedings_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedings_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedings_started_at'), ['started_at'], unique=False)

    op.create_table('health_events',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('photo_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_events_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_events_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_events_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('journal_entries',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('happened_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mood', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_happened_at'), ['happened_at'], unique=False)

    op.create_table('measurements',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurements_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_measured_at'), ['measured_at'], unique=False)

    op.create_table('medications',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('given_at', sa.DateTime(), nullable=False),
    sa.Column('med_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('dose_value', sa.Float(), nullable=False),
    sa.Column('dose_unit', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medications_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_medications_given_at'), ['given_at'], unique=False)

    op.create_table('milestones',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_observed_at'), ['observed_at'], unique=False)

    op.create_table('mother_logs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mother_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('photo_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['mother_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mother_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mother_logs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mother_logs_logged_at'), ['logged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mother_logs_mother_id'), ['mother_id'], unique=False)

    op.create_table('notes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_logged_at'), ['logged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_mother_id'), ['mother_id'], unique=False)

    op.create_table('photos',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('rel_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mime', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('uploader_user_id', sa.Integer(), nullable=True),
    sa.Column('linked_table', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('linked_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('thumb_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_taken_at'), ['taken_at'], unique=False)

    op.create_table('sleep_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('owlet_worn', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_sessions_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_sessions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_sessions_started_at'), ['started_at'], unique=False)

    op.create_table('vitals',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('agg', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('bucket_min', sa.Integer(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vitals_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vitals_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vitals_measured_at'), ['measured_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vitals_measured_at'))
        batch_op.drop_index(batch_op.f('ix_vitals_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_vitals_child_id'))

    op.drop_table('vitals')
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_sessions_started_at'))
        batch_op.drop_index(batch_op.f('ix_sleep_sessions_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_sleep_sessions_child_id'))

    op.drop_table('sleep_sessions')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_taken_at'))
        batch_op.drop_index(batch_op.f('ix_photos_deleted_at'))

    op.drop_table('photos')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_mother_id'))
        batch_op.drop_index(batch_op.f('ix_notes_logged_at'))
        batch_op.drop_index(batch_op.f('ix_notes_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_notes_child_id'))

    op.drop_table('notes')
    with op.batch_alter_table('mother_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mother_logs_mother_id'))
        batch_op.drop_index(batch_op.f('ix_mother_logs_logged_at'))
        batch_op.drop_index(batch_op.f('ix_mother_logs_deleted_at'))

    op.drop_table('mother_logs')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_observed_at'))
        batch_op.drop_index(batch_op.f('ix_milestones_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_milestones_child_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_given_at'))
        batch_op.drop_index(batch_op.f('ix_medications_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_medications_child_id'))

    op.drop_table('medications')
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_measured_at'))
        batch_op.drop_index(batch_op.f('ix_measurements_kind'))
        batch_op.drop_index(batch_op.f('ix_measurements_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_measurements_child_id'))

    op.drop_table('measurements')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_happened_at'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_child_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('health_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_events_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_health_events_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_health_events_child_id'))

    op.drop_table('health_events')
    with op.batch_alter_table('feedings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedings_started_at'))
        batch_op.drop_index(batch_op.f('ix_feedings_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_feedings_child_id'))

    op.drop_table('feedings')
    with op.batch_alter_table('diapers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diapers_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_diapers_child_id'))
        batch_op.drop_index(batch_op.f('ix_diapers_changed_at'))

    op.drop_table('diapers')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_mother_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_child_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('who_lms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_who_lms_sex'))
        batch_op.drop_index(batch_op.f('ix_who_lms_indicator'))
        batch_op.drop_index(batch_op.f('ix_who_lms_age_days'))

    op.drop_table('who_lms')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_ha_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_children_name'))
        batch_op.drop_index(batch_op.f('ix_children_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_children_birth_at'))

    op.drop_table('children')
    # ### end Alembic commands ###
