"""add notify_targets table

Revision ID: ebbb8202b0c2
Revises: 9391548d1d86
Create Date: 2026-04-22 06:12:21.841216+02:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ebbb8202b0c2'
down_revision: str | Sequence[str] | None = '9391548d1d86'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notify_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notify_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notify_targets_service_name'), ['service_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notify_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notify_targets_service_name'))

    op.drop_table('notify_targets')
    # ### end Alembic commands ###
